apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.deployment }}
  labels:
    {{- include "helm-hpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.names.deployment }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.deployment }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
