apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
  labels:
    {{- include "helm-hpa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.names.deployment }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
