apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-website-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app-website-v2
  template:
    metadata:
      labels:
        app: node-app-website-v2
    spec:
      containers:
        - name: node-app-website
          image: vinodhconnects/node-app-website
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: node-app-website-config
            - secretRef:
                name: node-app-website-secret
