apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-creation-read-all-namespaces
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["get"]
