apiVersion: v1
kind: Service
metadata:
  name: stateful-writer-headless
  namespace: workloads
spec:
  clusterIP: None
  selector:
    app: stateful-writer
  ports:
    - name: http
      port: 80
      targetPort: 8080
