apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-web
  namespace: pod-updates
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rolling-web
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rolling-web-svc
  namespace: pod-updates
spec:
  selector:
    app: rolling-web
  ports:
    - port: 80
      targetPort: 80
