apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-web
  namespace: pod-updates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recreate-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate-web
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recreate-web-svc
  namespace: pod-updates
spec:
  selector:
    app: recreate-web
  ports:
    - port: 80
      targetPort: 80
