apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-blue
  namespace: pod-updates
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluegreen-web
      color: blue
  template:
    metadata:
      labels:
        app: bluegreen-web
        color: blue
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-green
  namespace: pod-updates
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bluegreen-web
      color: green
  template:
    metadata:
      labels:
        app: bluegreen-web
        color: green
    spec:
      containers:
        - name: web
          image: nginx:1.28
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-active-svc
  namespace: pod-updates
spec:
  selector:
    app: bluegreen-web
    color: blue
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-preview-svc
  namespace: pod-updates
spec:
  selector:
    app: bluegreen-web
    color: green
  ports:
    - port: 80
      targetPort: 80
