apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-dev

resources:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: dev

images:
  - name: nginx
    newTag: "1.27.0"

patches:
  - path: patch-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_TITLE=Kustomize Demo (Dev)
      - APP_MESSAGE=Hello from DEV overlay
