apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-prod

resources:
  - ../../base

nameSuffix: -prod

commonLabels:
  environment: prod

images:
  - name: nginx
    newTag: "1.27.1"

patches:
  - path: patch-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_TITLE=Kustomize Demo (Prod)
      - APP_MESSAGE=Hello from PROD overlay
