apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v1
  namespace: gateway-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-v1
  template:
    metadata:
      labels:
        app: echo-v1
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:1.0.0
        args:
        - -text=echo-v1
        - -listen=:5678
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-v1-svc
  namespace: gateway-demo
spec:
  selector:
    app: echo-v1
  ports:
  - port: 80
    targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v2
  namespace: gateway-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-v2
  template:
    metadata:
      labels:
        app: echo-v2
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:1.0.0
        args:
        - -text=echo-v2
        - -listen=:5678
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-v2-svc
  namespace: gateway-demo
spec:
  selector:
    app: echo-v2
  ports:
  - port: 80
    targetPort: 5678
